// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1t189vbhEV2kFQGwpGKgttic1uKxc7nc',
    appId: '1:472899420623:web:1e9f7e0fdfcc912ec312ba',
    messagingSenderId: '472899420623',
    projectId: 'arbain-control',
    authDomain: 'arbain-control.firebaseapp.com',
    databaseURL: 'https://arbain-control-default-rtdb.firebaseio.com',
    storageBucket: 'arbain-control.firebasestorage.app',
    measurementId: 'G-WZMVZ2KPEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67z7V5FfvMPIMIAta8_Ha9TmYJnph190',
    appId: '1:472899420623:android:de48e103367855e0c312ba',
    messagingSenderId: '472899420623',
    projectId: 'arbain-control',
    databaseURL: 'https://arbain-control-default-rtdb.firebaseio.com',
    storageBucket: 'arbain-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYlC31eoWaKlAAKD_H3toWS-N6AE5gWHg',
    appId: '1:472899420623:ios:cd75f4bca2b6dab7c312ba',
    messagingSenderId: '472899420623',
    projectId: 'arbain-control',
    databaseURL: 'https://arbain-control-default-rtdb.firebaseio.com',
    storageBucket: 'arbain-control.firebasestorage.app',
    iosBundleId: 'com.example.arbainAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYlC31eoWaKlAAKD_H3toWS-N6AE5gWHg',
    appId: '1:472899420623:ios:cd75f4bca2b6dab7c312ba',
    messagingSenderId: '472899420623',
    projectId: 'arbain-control',
    databaseURL: 'https://arbain-control-default-rtdb.firebaseio.com',
    storageBucket: 'arbain-control.firebasestorage.app',
    iosBundleId: 'com.example.arbainAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1t189vbhEV2kFQGwpGKgttic1uKxc7nc',
    appId: '1:472899420623:web:b91fbd166ea0e825c312ba',
    messagingSenderId: '472899420623',
    projectId: 'arbain-control',
    authDomain: 'arbain-control.firebaseapp.com',
    databaseURL: 'https://arbain-control-default-rtdb.firebaseio.com',
    storageBucket: 'arbain-control.firebasestorage.app',
    measurementId: 'G-NF83Z7XDFH',
  );
}
